# Generated by Django 2.1 on 2022-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220315_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='head_image',
            field=models.ImageField(default='static/user_image/default.jpg', upload_to='user_image/%Y/%m', verbose_name='头像'),
        ),
    ]
