# Generated by Django 2.1 on 2022-03-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220322_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'verbose_name': '用户档案', 'verbose_name_plural': '用户档案'},
        ),
    ]
