# Generated by Django 2.1 on 2022-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('book_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='book_id')),
                ('cover', models.ImageField(blank=True, default='static/book_image/default.jpg', null=True, upload_to='book_image/%Y/%m', verbose_name='封面')),
                ('title', models.CharField(max_length=80, verbose_name='书名')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='定价')),
                ('new_old', models.BooleanField(choices=[(0, '新'), (1, '旧')], default=0, verbose_name='新旧')),
                ('state', models.BooleanField(choices=[(0, '在售'), (1, '下架')], default=0, verbose_name='状态')),
                ('publisher', models.CharField(max_length=80, verbose_name='出版社')),
                ('p_date', models.DateField(blank=True, null=True, verbose_name='出版时间')),
                ('classi', models.CharField(max_length=10, verbose_name='分类')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='内容简介')),
                ('trading_volume', models.IntegerField(default=0, verbose_name='交易量')),
                ('collection_volume', models.IntegerField(default=0, verbose_name='收藏量')),
                ('hit_volume', models.IntegerField(default=0, verbose_name='点击量')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
            ],
        ),
    ]
