# Generated by Django 2.1 on 2022-03-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220322_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshit',
            name='c_time',
        ),
        migrations.AddField(
            model_name='bookshit',
            name='h_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookscollect',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.BooksInfo', verbose_name='book_id'),
        ),
        migrations.AlterField(
            model_name='bookscollect',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookscollect',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='bookshit',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.BooksInfo', verbose_name='book_id'),
        ),
        migrations.AlterField(
            model_name='bookshit',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
    ]
