# Generated by Django 2.1 on 2022-03-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220323_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookscollect',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookscollect',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bookshit',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookshit',
            old_name='user_id',
            new_name='user',
        ),
    ]
