# Generated by Django 2.1 on 2022-03-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_auto_20220323_0033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsInfo',
            fields=[
                ('cart_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='cart_id')),
                ('book_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='书籍单价')),
                ('cart_quantity', models.IntegerField(default=1, verbose_name='入车数量')),
                ('cart_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='入车总额')),
                ('cart_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.BooksInfo', verbose_name='book_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name': '购物车信息',
                'verbose_name_plural': '购物车信息',
            },
        ),
    ]
