# Generated by Django 2.1 on 2022-03-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartsinfo',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='cartsinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
