# Generated by Django 2.1 on 2022-03-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_auto_20220323_0033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersInfo',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='order_id')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='书籍单价')),
                ('o_quantity', models.IntegerField(default=0, verbose_name='购入数量')),
                ('o_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单总额')),
                ('o_state', models.IntegerField(choices=[(0, '待付款'), (1, '已付款'), (2, '待发货'), (3, '待收货'), (4, '已完成')], default=0, verbose_name='订单状态')),
                ('o_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.BooksInfo', verbose_name='book_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name': '购入信息',
                'verbose_name_plural': '购入信息',
            },
        ),
        migrations.CreateModel(
            name='SellInfo',
            fields=[
                ('sell_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='sell_id')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='书籍单价')),
                ('s_quantity', models.IntegerField(default=0, verbose_name='卖出数量')),
                ('s_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='卖单总额')),
                ('s_state', models.IntegerField(choices=[(0, '待发布'), (1, '待审核'), (2, '已完成')], default=0, verbose_name='卖单状态')),
                ('s_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.BooksInfo', verbose_name='book_id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'verbose_name': '卖出信息',
                'verbose_name_plural': '卖出信息',
            },
        ),
    ]
